In [4]:
import pandas as pd

In [5]:
nyc=pd.read_csv('ave_hi_nyc_jan_1895-2018.csv.xls', header='infer')

In [6]:
nyc

Date  Value  Anomaly
0    189501   34.2     -3.2
1    189601   34.7     -2.7
2    189701   35.5     -1.9
3    189801   39.6      2.2
4    189901   36.4     -1.0
..      ...    ...      ...
119  201401   35.5     -1.9
120  201501   36.1     -1.3
121  201601   40.8      3.4
122  201701   42.8      5.4
123  201801   38.7      1.3

[124 rows x 3 columns]

In [7]:
nyc.columns

Index(['Date', 'Value', 'Anomaly'], dtype='object')

In [8]:
nyc.columns=['Date', 'Temperature', 'Anomaly']

In [9]:
nyc.head(6)

Date  Temperature  Anomaly
0  189501         34.2     -3.2
1  189601         34.7     -2.7
2  189701         35.5     -1.9
3  189801         39.6      2.2
4  189901         36.4     -1.0
5  190001         37.4      0.0

In [11]:
nyc.sample(9)
nyc.tail(3)

Date  Temperature  Anomaly
121  201601         40.8      3.4
122  201701         42.8      5.4
123  201801         38.7      1.3

In [12]:
nyc.shape

(124, 3)

In [14]:
nyc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124 entries, 0 to 123
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Date         124 non-null    int64  
 1   Temperature  124 non-null    float64
 2   Anomaly      124 non-null    float64
dtypes: float64(2), int64(1)
memory usage: 3.0 KB


In [15]:
nyc.Date=nyc.Date.floordiv(100)

In [16]:
nyc.head(10)


Date  Temperature  Anomaly
0  1895         34.2     -3.2
1  1896         34.7     -2.7
2  1897         35.5     -1.9
3  1898         39.6      2.2
4  1899         36.4     -1.0
5  1900         37.4      0.0
6  1901         37.0     -0.4
7  1902         35.0     -2.4
8  1903         35.5     -1.9
9  1904         29.8     -7.6

Date is an independent variable - Temperature is dependent so its the y 
It becomes Temperature = m*Date+C

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
nyc['Date'].values

array([1895, 1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905,
       1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916,
       1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927,
       1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938,
       1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949,
       1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960,
       1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971,
       1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982,
       1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993,
       1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004,
       2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
       2016, 2017, 2018])

In [19]:
nyc['Temperature'].values

array([34.2, 34.7, 35.5, 39.6, 36.4, 37.4, 37. , 35. , 35.5, 29.8, 33.7,
       42.3, 40.5, 38.3, 39.6, 36.1, 40.7, 29.3, 46.9, 36.9, 38.9, 42.3,
       38.4, 26.5, 40.6, 29.7, 39.7, 33.4, 35.2, 39.4, 33.8, 37.2, 36.8,
       40. , 37.8, 38.5, 38.2, 47.6, 45.6, 39.8, 35. , 34.3, 45.7, 37.3,
       36.8, 30. , 34.5, 36.5, 36.1, 39. , 31.5, 40.2, 43. , 30.1, 43.5,
       47.6, 42.5, 42.4, 42.4, 37. , 35.6, 36.2, 33.8, 36.4, 37.1, 37.8,
       31.9, 38. , 34.6, 40.2, 34. , 37.1, 41.6, 31.7, 35.7, 29.9, 31.5,
       40.5, 40.6, 39.7, 41.7, 32.6, 26.1, 32.3, 38.6, 38. , 30.6, 30.9,
       38. , 33.5, 33. , 39.3, 35.9, 34.2, 42.4, 46. , 39.6, 40.9, 41. ,
       31.6, 42.6, 37. , 39.2, 45.8, 40.8, 37.8, 38.8, 45.4, 32.9, 31. ,
       37.4, 47.6, 43.6, 42.4, 33.4, 38.1, 34.8, 44.2, 40.8, 35.5, 36.1,
       40.8, 42.8, 38.7])

In [20]:
type(nyc['Date'].values)

numpy.ndarray

In [21]:
import numpy as np

In [22]:
m=np.linspace(1,5,10)

In [23]:
m

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [24]:
m.shape

(10,)

In [25]:
m.reshape(-1,1).shape

(10, 1)

In [29]:
X_train, X_test, y_train, y_test=train_test_split(nyc.Date.values.reshape(-1,1),nyc.Temperature.values, test_size=0.2, random_state=11)

In [30]:
X_train.shape

(99, 1)

In [31]:
X_test.shape

(25, 1)

In [32]:
99/124*100

79.83870967741935

In [33]:
X_train[0]

array([1957])

In [35]:
y_train[0]

np.float64(33.8)

In [36]:
from sklearn.linear_model import LinearRegression

In [37]:
linear_regression=LinearRegression()

In [38]:
linear_regression

LinearRegression()

In [40]:
linear_regression.fit(X=X_train, y=y_train)

LinearRegression()